// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5hma8Y5uVWKnG0kOzurCRedMR9Er1uCM',
    appId: '1:147092371359:web:c1b19254fbd5b6a94dafaa',
    messagingSenderId: '147092371359',
    projectId: 'wits-services-ea5cf',
    authDomain: 'wits-services-ea5cf.firebaseapp.com',
    storageBucket: 'wits-services-ea5cf.appspot.com',
    measurementId: 'G-X5FB57K5QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi_Mkh33Qjsms3Uc9FF9vjQpLxxAySA4s',
    appId: '1:147092371359:android:43a850871aa98f3a4dafaa',
    messagingSenderId: '147092371359',
    projectId: 'wits-services-ea5cf',
    storageBucket: 'wits-services-ea5cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1gm216VKwqEq3oApesCakwxisuWXtkdk',
    appId: '1:147092371359:ios:965079659a06fc524dafaa',
    messagingSenderId: '147092371359',
    projectId: 'wits-services-ea5cf',
    storageBucket: 'wits-services-ea5cf.appspot.com',
    androidClientId: '147092371359-pkkcuckdmm25t2kvkmpc03tvcgjhfnba.apps.googleusercontent.com',
    iosClientId: '147092371359-m21g7893ja5n4340ne7447bs5bs7gdgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.witsStudentsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1gm216VKwqEq3oApesCakwxisuWXtkdk',
    appId: '1:147092371359:ios:965079659a06fc524dafaa',
    messagingSenderId: '147092371359',
    projectId: 'wits-services-ea5cf',
    storageBucket: 'wits-services-ea5cf.appspot.com',
    androidClientId: '147092371359-pkkcuckdmm25t2kvkmpc03tvcgjhfnba.apps.googleusercontent.com',
    iosClientId: '147092371359-m21g7893ja5n4340ne7447bs5bs7gdgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.witsStudentsApp',
  );
}
