// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLpe6Lt0rD5IDB_xdqTDakoKoU-F0MO1I',
    appId: '1:611448757567:web:d9d5abd81a28448ae1078a',
    messagingSenderId: '611448757567',
    projectId: 'studentsapp-96c77',
    authDomain: 'studentsapp-96c77.firebaseapp.com',
    storageBucket: 'studentsapp-96c77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdhNqngRf0TPahWjvByL1iWDkeHyE3RE8',
    appId: '1:611448757567:android:867e26c7a9446700e1078a',
    messagingSenderId: '611448757567',
    projectId: 'studentsapp-96c77',
    storageBucket: 'studentsapp-96c77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdJcj4tB6jikS2qNSWqxWup2cML76v-F8',
    appId: '1:611448757567:ios:f5cd96fc51898742e1078a',
    messagingSenderId: '611448757567',
    projectId: 'studentsapp-96c77',
    storageBucket: 'studentsapp-96c77.appspot.com',
    iosClientId: '611448757567-o0qa520c4v0dfpbbbq6vebksl02gdp6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdJcj4tB6jikS2qNSWqxWup2cML76v-F8',
    appId: '1:611448757567:ios:f5cd96fc51898742e1078a',
    messagingSenderId: '611448757567',
    projectId: 'studentsapp-96c77',
    storageBucket: 'studentsapp-96c77.appspot.com',
    iosClientId: '611448757567-o0qa520c4v0dfpbbbq6vebksl02gdp6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentsApp',
  );
}
